services:
  worker-0:
    build:
      args:
        LLAMA_WORKER_BASE_IMAGE: ${LLAMA_WORKER_BASE_IMAGE:-ghcr.io/ggml-org/llama.cpp:server-vulkan}
    devices:
      - /dev/dri:/dev/dri
  worker-1:
    build:
      args:
        LLAMA_WORKER_BASE_IMAGE: ${LLAMA_WORKER_BASE_IMAGE:-ghcr.io/ggml-org/llama.cpp:server-vulkan}
    devices:
      - /dev/dri:/dev/dri
