package openaiapi

import gen "github.com/vex9z7/llama.cpp-stack/gateway/internal/openaiapi/generated"

type ChatCompletion = gen.ChatCompletion
type ChatCompletionAssistantContent = gen.ChatCompletionAssistantContent
type ChatCompletionCreateRequest = gen.ChatCompletionCreateRequest
type ChatCompletionRequestAssistantMessage = gen.ChatCompletionRequestAssistantMessage
type ChatCompletionRequestAssistantMessageContentPart = gen.ChatCompletionRequestAssistantMessageContentPart
type ChatCompletionRequestDeveloperMessage = gen.ChatCompletionRequestDeveloperMessage
type ChatCompletionRequestMessage = gen.ChatCompletionRequestMessage
type ChatCompletionRequestMessageContentPartImage = gen.ChatCompletionRequestMessageContentPartImage
type ChatCompletionRequestMessageContentPartImageURL = gen.ChatCompletionRequestMessageContentPartImageURL
type ChatCompletionRequestMessageContentPartImageURLDetail = gen.ChatCompletionRequestMessageContentPartImageURLDetail
type ChatCompletionRequestMessageContentPartImageType = gen.ChatCompletionRequestMessageContentPartImageType
type ChatCompletionRequestMessageContentPartRefusal = gen.ChatCompletionRequestMessageContentPartRefusal
type ChatCompletionRequestMessageContentPartText = gen.ChatCompletionRequestMessageContentPartText
type ChatCompletionRequestSystemMessage = gen.ChatCompletionRequestSystemMessage
type ChatCompletionRequestToolMessage = gen.ChatCompletionRequestToolMessage
type ChatCompletionRequestUserMessage = gen.ChatCompletionRequestUserMessage
type ChatCompletionRequestUserMessageContentPart = gen.ChatCompletionRequestUserMessageContentPart
type ChatCompletionTextContent = gen.ChatCompletionTextContent
type ChatCompletionUserContent = gen.ChatCompletionUserContent
type Completion = gen.Completion
type CompletionTokensDetails = gen.CompletionTokensDetails
type CompletionUsage = gen.CompletionUsage
type EasyInputMessage = gen.EasyInputMessage
type EasyInputMessageContent = gen.EasyInputMessageContent
type EasyInputMessageRole = gen.EasyInputMessageRole
type EasyInputMessageType = gen.EasyInputMessageType
type EmbeddingResponse = gen.EmbeddingResponse
type EmbeddingUsage = gen.EmbeddingUsage
type ErrorBody = gen.ErrorBody
type ErrorObject = gen.ErrorObject
type InputMessageContent = gen.InputMessageContent
type InputMessageContentType = gen.InputMessageContentType
type Model = gen.Model
type ModelList = gen.ModelList
type ModelMeta = gen.ModelMeta
type ModelRequest = gen.ModelRequest
type PromptTokensDetails = gen.PromptTokensDetails
type Response = gen.Response
type ResponseObject = gen.ResponseObject
type ResponseStatus = gen.ResponseStatus
type ResponseCompletedEvent = gen.ResponseCompletedEvent
type ResponseCompletedEventType = gen.ResponseCompletedEventType
type ResponseCreateRequest = gen.ResponseCreateRequest
type ResponseFunctionCall = gen.ResponseFunctionCall
type ResponseFunctionCallArgumentsDeltaEvent = gen.ResponseFunctionCallArgumentsDeltaEvent
type ResponseFunctionCallArgumentsDoneEvent = gen.ResponseFunctionCallArgumentsDoneEvent
type ResponseFunctionCallArgumentsDoneEventType = gen.ResponseFunctionCallArgumentsDoneEventType
type ResponseFunctionCallOutput = gen.ResponseFunctionCallOutput
type ResponseInput = gen.ResponseInput
type ResponseInputItem = gen.ResponseInputItem
type ResponseInputTokensDetails = gen.ResponseInputTokensDetails
type ResponseOutputTokensDetails = gen.ResponseOutputTokensDetails
type ResponseOutputFunctionCallItem = gen.ResponseOutputFunctionCallItem
type ResponseOutputFunctionCallItemStatus = gen.ResponseOutputFunctionCallItemStatus
type ResponseOutputFunctionCallItemType = gen.ResponseOutputFunctionCallItemType
type ResponseOutputItem = gen.ResponseOutputItem
type ResponseOutputItemDoneEvent = gen.ResponseOutputItemDoneEvent
type ResponseOutputMessageContent = gen.ResponseOutputMessageContent
type ResponseOutputMessageItem = gen.ResponseOutputMessageItem
type ResponseOutputMessageItemRole = gen.ResponseOutputMessageItemRole
type ResponseOutputMessageItemStatus = gen.ResponseOutputMessageItemStatus
type ResponseOutputMessageItemType = gen.ResponseOutputMessageItemType
type ResponseOutputReasoningContent = gen.ResponseOutputReasoningContent
type ResponseOutputReasoningContentType = gen.ResponseOutputReasoningContentType
type ResponseOutputReasoningItem = gen.ResponseOutputReasoningItem
type ResponseOutputReasoningItemStatus = gen.ResponseOutputReasoningItemStatus
type ResponseOutputReasoningItemType = gen.ResponseOutputReasoningItemType
type ResponseOutputSummaryTextContent = gen.ResponseOutputSummaryTextContent
type ResponseOutputSummaryTextContentType = gen.ResponseOutputSummaryTextContentType
type ResponseOutputTextContent = gen.ResponseOutputTextContent
type ResponseOutputTextContentType = gen.ResponseOutputTextContentType
type ResponseRefusalContent = gen.ResponseRefusalContent
type ResponseRefusalContentType = gen.ResponseRefusalContentType
type ResponseUsage = gen.ResponseUsage

const (
	EasyInputMessageRoleAssistant EasyInputMessageRole = gen.EasyInputMessageRoleAssistant
	EasyInputMessageRoleDeveloper EasyInputMessageRole = gen.EasyInputMessageRoleDeveloper
	EasyInputMessageRoleSystem    EasyInputMessageRole = gen.EasyInputMessageRoleSystem
	EasyInputMessageRoleUser      EasyInputMessageRole = gen.EasyInputMessageRoleUser

	EasyInputMessageTypeMessage EasyInputMessageType = gen.EasyInputMessageTypeMessage

	InputMessageContentTypeInputText  InputMessageContentType = gen.InputMessageContentTypeInputText
	InputMessageContentTypeOutputText InputMessageContentType = gen.InputMessageContentTypeOutputText

	ResponseCompletedEventTypeCompleted            ResponseCompletedEventType                 = gen.ResponseCompleted
	ResponseFunctionCallArgumentsDoneEventTypeDone ResponseFunctionCallArgumentsDoneEventType = gen.ResponseFunctionCallArgumentsDone
	ResponseOutputFunctionCallItemTypeFunctionCall ResponseOutputFunctionCallItemType         = gen.ResponseOutputFunctionCallItemTypeFunctionCall
)
