#!/usr/bin/env python3
"""Static checks that gateway API boundary uses generated schema types."""
from __future__ import annotations

import re
import sys
from pathlib import Path


def fail(msg: str) -> None:
    raise AssertionError(msg)


def read(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")


def require(condition: bool, msg: str) -> None:
    if not condition:
        fail(msg)


def check_generated_types() -> None:
    for path in [
        Path("gateway/internal/openaiapi/generated/types.gen.go"),
        Path("gateway/internal/llamacppapi/generated/types.gen.go"),
    ]:
        text = path.read_text(encoding="utf-8")
        require("Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT." in text,
                f"{path} is not generated by pinned oapi-codegen v2.7.0")


def check_openai_aliases() -> None:
    text = read("gateway/internal/openaiapi/aliases.go")
    require('import gen "github.com/vex9z7/llama.cpp-stack/gateway/internal/openaiapi/generated"' in text,
            "openaiapi aliases must import generated package")
    for name in [
        "ChatCompletion", "Completion", "CompletionUsage", "EasyInputMessage", "EasyInputMessageContent",
        "EasyInputMessageRole", "EasyInputMessageType", "EmbeddingResponse", "EmbeddingUsage",
        "ErrorBody", "ErrorObject", "InputMessageContent", "InputMessageContentType", "Model",
        "ModelList", "ModelMeta", "ModelRequest", "PromptTokensDetails", "Response",
        "ResponseCreateRequest", "ResponseFunctionCall", "ResponseFunctionCallArgumentsDeltaEvent",
        "ResponseFunctionCallArgumentsDoneEvent", "ResponseFunctionCallOutput",
        "ResponseInput", "ResponseInputItem", "ResponseInputTokensDetails",
        "ResponseObject", "ResponseStatus", "ResponseOutputFunctionCallItem",
        "ResponseOutputFunctionCallItemStatus", "ResponseOutputFunctionCallItemType",
        "ResponseOutputItem", "ResponseOutputItemDoneEvent", "ResponseOutputMessageContent",
        "ResponseOutputMessageItem", "ResponseOutputMessageItemRole", "ResponseOutputMessageItemStatus",
        "ResponseOutputMessageItemType", "ResponseOutputReasoningContent", "ResponseOutputReasoningContentType",
        "ResponseOutputReasoningItem", "ResponseOutputReasoningItemStatus", "ResponseOutputReasoningItemType",
        "ResponseOutputSummaryTextContent", "ResponseOutputSummaryTextContentType",
        "ResponseOutputTextContent", "ResponseOutputTextContentType", "ResponseOutputTokensDetails",
        "ResponseRefusalContent", "ResponseRefusalContentType", "ResponseUsage",
    ]:
        require(f"type {name} = gen.{name}" in text, f"openaiapi.{name} must alias generated type")


def check_llamacpp_aliases() -> None:
    text = read("gateway/internal/llamacppapi/aliases.go")
    require('import gen "github.com/vex9z7/llama.cpp-stack/gateway/internal/llamacppapi/generated"' in text,
            "llamacppapi aliases must import generated package")
    for name in ["ChatCompletion", "Completion", "CompletionUsage", "EmbeddingResponse", "EmbeddingUsage", "ModelList", "ModelRequest", "Response", "ResponseOutputItem", "ResponseUsage", "Success"]:
        require(f"type {name} = gen.{name}" in text, f"llamacppapi.{name} must alias generated type")


def check_no_handwritten_shadow_types() -> None:
    banned = {
        "gateway/internal/openaiapi/common.go",
        "gateway/internal/openaiapi/generation.go",
        "gateway/internal/openaiapi/models.go",
        "gateway/internal/openaiapi/requests.go",
        "gateway/internal/openaiapi/responses.go",
        "gateway/internal/llamacppapi/generation.go",
        "gateway/internal/llamacppapi/responses.go",
    }
    existing = [path for path in banned if Path(path).exists()]
    require(not existing, f"handwritten API type files shadow generated types: {existing}")


def check_adapter_imports_and_normalization() -> None:
    for path in [Path("gateway/internal/apiadapter/responses.go"), Path("gateway/internal/apiadapter/generation.go")]:
        text = path.read_text(encoding="utf-8")
        require("gateway/internal/llamacppapi" in text, f"{path} must consume llamacppapi types")
        require("gateway/internal/openaiapi" in text, f"{path} must produce openaiapi types")
        require("map[string]any" not in text, f"{path} should not use untyped map[string]any")

    requests = read("gateway/internal/apiadapter/requests.go")
    require("openaiapi.ResponseCreateRequest" in requests, "Responses request adapter must consume generated OpenAI request type")
    require("openaiapi.ResponseInputItem" in requests, "Responses request adapter must normalize generated input items")
    require("openaiapi.InputMessageContent" in requests, "Responses request adapter must emit typed message content")
    require("InputMessageContentTypeOutputText" in requests, "Responses request adapter must normalize assistant string history to output_text")
    require("InputMessageContentTypeInputText" in requests, "Responses request adapter must normalize user/system/developer string input to input_text")
    require("map[string]any" not in requests, "Responses request adapter should not use untyped map[string]any")

    responses = read("gateway/internal/apiadapter/responses.go")
    require("OutputTokensDetails: openaiapi.ResponseOutputTokensDetails{ReasoningTokens: 0}" in responses,
            "Responses adapter must fill OpenAI output_tokens_details.reasoning_tokens")
    require("[]llamacppapi.ResponseOutputItem" in responses and "[]openaiapi.ResponseOutputItem" in responses,
            "Responses adapter must bridge typed upstream output items to typed OpenAI output items")
    generation = read("gateway/internal/apiadapter/generation.go")
    require("CompletionTokensDetails: openaiapi.CompletionTokensDetails{ReasoningTokens: 0}" in generation,
            "Completion adapter must fill OpenAI completion_tokens_details.reasoning_tokens")


def check_server_boundary() -> None:
    text = read("gateway/internal/server/handlers.go")
    require("openaiapi.ModelRequest" in text, "server must parse requests through openaiapi.ModelRequest")
    require("openaiapi.ModelList" in text, "server /v1/models must use openaiapi.ModelList")
    require("openaiapi.ErrorBody" in text, "server errors must use openaiapi.ErrorBody")
    require("map[string]any{\"error\"" not in text, "server must not hand-roll OpenAI error maps")

    handler = read("gateway/internal/server/handlers.go")
    require("adaptRequestBody(ctx.URL().Path, body)" in handler, "server must adapt OpenAI request bodies before proxying upstream")

    request_adapter = read("gateway/internal/server/request_adapter.go")
    require("apiadapter.AdaptResponsesRequestBody" in request_adapter, "request adapter must call apiadapter.AdaptResponsesRequestBody")

    response_adapter = read("gateway/internal/server/response_adapter.go")
    responses_sse_adapter = read("gateway/internal/server/responses_sse_adapter.go")
    require("openaiapi.ResponseFunctionCallArgumentsDoneEvent" in responses_sse_adapter, "Responses SSE adapter must emit typed function_call_arguments.done events")
    require("response.function_call_arguments.delta" in responses_sse_adapter, "Responses SSE adapter must observe function call argument deltas")
    require("response.output_item.done" in responses_sse_adapter, "Responses SSE adapter must inject arguments.done before output_item.done")
    require("openaiapi.ResponseOutputItemDoneEvent" in responses_sse_adapter, "Responses SSE adapter must parse output_item.done through generated event type")
    require("openaiapi.ResponseOutputFunctionCallItem" in responses_sse_adapter, "Responses SSE adapter must parse typed function_call output items")
    require("CallId" in responses_sse_adapter, "Responses SSE adapter must use typed function_call call_id")
    for fn in ["apiadapter.AdaptChatCompletionBody", "apiadapter.AdaptCompletionBody", "apiadapter.AdaptResponsesBody", "apiadapter.AdaptEmbeddingBody"]:
        require(fn in response_adapter, f"response adapter must call {fn}")
    require("apiadapter.AdaptResponsesSSEPayload" in responses_sse_adapter, "Responses SSE adapter must call apiadapter.AdaptResponsesSSEPayload")


def check_openai_schema_request_contract() -> None:
    schema = read("openai-api-schema.yaml")
    require("generated_by: scripts/generate_openai_gateway_schema.py" in schema, "OpenAI gateway schema must be generated from the vendored OpenAI snapshot")
    require("$ref: '#/components/schemas/ResponseCreateRequest'" in schema, "/v1/responses request must use ResponseCreateRequest, not bare ModelRequest")
    for name in ["EasyInputMessage", "ResponseInputItem", "ResponseFunctionCall", "ResponseFunctionCallOutput", "ResponseFunctionCallArgumentsDeltaEvent", "ResponseFunctionCallArgumentsDoneEvent", "ResponseOutputItem", "ResponseOutputFunctionCallItem", "ResponseOutputMessageItem", "ResponseOutputMessageContent", "ResponseOutputTextContent", "ResponseRefusalContent", "ResponseOutputReasoningItem", "ResponseOutputReasoningContent", "ResponseOutputSummaryTextContent", "ResponseOutputItemDoneEvent"]:
        require(f"    {name}:" in schema, f"OpenAI gateway schema must include {name}")
    for source in ["CreateResponse", "FunctionToolCall", "FunctionToolCallOutput", "OutputItem", "OutputMessage", "OutputMessageContent", "OutputTextContent", "RefusalContent", "ReasoningItem", "ResponseUsage"]:
        require(f"x-oai-source: {source}" in schema, f"OpenAI gateway schema must anchor generated subset to official {source}")
    require("item:\n          $ref: '#/components/schemas/ResponseOutputItem'" in schema, "ResponseOutputItemDoneEvent.item must not be an untyped object")
    require("required: [type, call_id, name, arguments]" in schema, "ResponseOutputFunctionCallItem must require call_id/name/arguments")
    require("output:\n          type: array\n          items:\n            $ref: '#/components/schemas/ResponseOutputItem'" in schema, "OpenAI Response.output must be typed as ResponseOutputItem array")
    require("summary:\n          type: array\n          items:\n            $ref: '#/components/schemas/ResponseOutputSummaryTextContent'" in schema, "Reasoning summary items must be typed")


def check_tool_pin() -> None:
    gomod = read("go.mod")
    require("github.com/oapi-codegen/oapi-codegen/v2 v2.7.0" in gomod, "go.mod must pin oapi-codegen v2.7.0")
    script = read("scripts/generate_api_types.sh")
    require('VERSION="v2.7.0"' in script, "generate script must pin oapi-codegen v2.7.0")
    require("llamacpp-api-schema/openapi.yaml" in script, "generate script must use llama.cpp schema")
    require("generate_openai_gateway_schema.py" in script, "generate script must regenerate OpenAI gateway schema from vendored OpenAI snapshot")
    require("openai-openapi/spec/openapi.documented.yml" in script, "generate script must read vendored OpenAI OpenAPI snapshot")
    require("openai-api-schema.yaml" in script, "generate script must use generated OpenAI gateway schema")
    require("types,skip-prune" in script, "generate script must preserve typed event schemas used by streaming adapters")


def main() -> int:
    check_generated_types()
    check_openai_aliases()
    check_llamacpp_aliases()
    check_no_handwritten_shadow_types()
    check_adapter_imports_and_normalization()
    check_server_boundary()
    check_openai_schema_request_contract()
    check_tool_pin()
    print("gateway typed boundary checks passed.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        raise
