#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = ROOT / "configs" / "instances.toml"
EXAMPLE_CONFIG = ROOT / "configs" / "instances.example.toml"
DEFAULT_OUTPUT = ROOT / "docker-compose.instances.yml"
SUPPORTED_BACKENDS = {"cpu", "vulkan", "cuda"}
IMAGES = {
    "cpu": "ghcr.io/ggml-org/llama.cpp:server",
    "vulkan": "ghcr.io/ggml-org/llama.cpp:server-vulkan",
    "cuda": "ghcr.io/ggml-org/llama.cpp:server-cuda",
}


def q(value: Any) -> str:
    s = str(value)
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def service_name(name: str) -> str:
    out = re.sub(r"[^a-zA-Z0-9_-]+", "-", name.strip()).strip("-").lower()
    if not out:
        raise SystemExit("instance name cannot be empty")
    return "llama-" + out


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Missing {path}. Copy {EXAMPLE_CONFIG.relative_to(ROOT)} to {path.relative_to(ROOT)} first.")
    return tomllib.loads(path.read_text())


def merged_instances(config: dict[str, Any]) -> list[dict[str, Any]]:
    defaults = config.get("defaults", {})
    instances = []
    seen_ports: set[int] = set()
    seen_names: set[str] = set()
    for raw in config.get("instances", []):
        item = {**defaults, **raw}
        if not item.get("enabled", True):
            continue
        name = item.get("name")
        if not name:
            raise SystemExit("each instance needs name")
        svc = service_name(str(name))
        if svc in seen_names:
            raise SystemExit(f"duplicate instance service name: {svc}")
        seen_names.add(svc)
        backend = item.get("backend", "vulkan")
        if backend not in SUPPORTED_BACKENDS:
            raise SystemExit(f"unsupported backend for {name}: {backend}")
        port = int(item.get("port", 0))
        if port <= 0:
            raise SystemExit(f"instance {name} needs positive port")
        if port in seen_ports:
            raise SystemExit(f"duplicate host port: {port}")
        seen_ports.add(port)
        if not item.get("model_file"):
            raise SystemExit(f"instance {name} needs model_file")
        if not item.get("alias"):
            item["alias"] = name
        instances.append(item)
    if not instances:
        raise SystemExit("no enabled instances")
    return instances


def render(config_path: Path, output_path: Path) -> None:
    instances = merged_instances(load_config(config_path))
    lines: list[str] = [
        "# Generated by scripts/render_instances.py; do not edit by hand.",
        "services:",
    ]
    for item in instances:
        name = str(item["name"])
        svc = service_name(name)
        backend = str(item.get("backend", "vulkan"))
        image = str(item.get("image") or IMAGES[backend])
        host = str(item.get("host", "127.0.0.1"))
        port = int(item["port"])
        model = str(item["model_file"])
        alias = str(item.get("alias", name))
        ctx_size = int(item.get("ctx_size", 8192))
        parallel = int(item.get("parallel", 1))
        threads_http = int(item.get("threads_http", -1))
        n_gpu_layers = int(item.get("n_gpu_layers", 999))
        extra_args = str(item.get("extra_args", "")).strip()
        cmd = (
            "--host 0.0.0.0 --port 8080 "
            f"--model /models/{model} --alias {alias} "
            f"--ctx-size {ctx_size} --parallel {parallel} "
            f"--threads-http {threads_http} --n-gpu-layers {n_gpu_layers} "
            "--cont-batching --cache-prompt"
        )
        if extra_args:
            cmd += " " + extra_args
        lines += [
            f"  {svc}:",
            f"    image: {image}",
            f"    container_name: {svc}",
            "    restart: unless-stopped",
            "    ports:",
            f"      - {q(f'{host}:{port}:8080')}",
            "    volumes:",
            "      - ./models:/models:ro,Z",
            "    security_opt:",
            "      - no-new-privileges:true",
            "    tmpfs:",
            "      - /tmp:size=512m,mode=1777",
            "    ipc: host",
            f"    command: {q(cmd)}",
        ]
        if backend == "vulkan":
            lines += ["    devices:", "      - /dev/dri:/dev/dri"]
        elif backend == "cuda":
            lines += [
                "    deploy:",
                "      resources:",
                "        reservations:",
                "          devices:",
                "            - driver: nvidia",
                "              count: all",
                "              capabilities: [gpu]",
            ]
        lines += [
            "    healthcheck:",
            "      test:",
            "        - CMD-SHELL",
            "        - bash -lc '</dev/tcp/127.0.0.1/8080'",
            "      interval: 30s",
            "      timeout: 5s",
            "      retries: 10",
            "      start_period: 60s",
            "    stop_grace_period: 30s",
        ]
    output_path.write_text("\n".join(lines) + "\n")

    try:
        display_path = output_path.relative_to(ROOT)
    except ValueError:
        display_path = output_path
    print(f"rendered {display_path} with {len(instances)} instance(s)")


def check(config_path: Path) -> None:
    instances = merged_instances(load_config(config_path))
    ok = True
    needs_vulkan = False
    needs_cuda = False
    for item in instances:
        model = ROOT / "models" / str(item["model_file"])
        if not model.exists():
            print(f"missing model for {item['name']}: {model.relative_to(ROOT)}", file=sys.stderr)
            ok = False
        needs_vulkan = needs_vulkan or item.get("backend", "vulkan") == "vulkan"
        needs_cuda = needs_cuda or item.get("backend") == "cuda"
    if needs_vulkan and not Path("/dev/dri").exists():
        print("missing /dev/dri for Vulkan instances", file=sys.stderr)
        ok = False
    if needs_cuda:
        # Avoid importing shutil just for this check.
        import shutil
        if not shutil.which("nvidia-smi"):
            print("nvidia-smi not found for CUDA instances", file=sys.stderr)
            ok = False
    if not ok:
        raise SystemExit(2)
    print(f"instances ok: {len(instances)} enabled")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["render", "check"])
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()
    config_path = Path(args.config)
    output_path = Path(args.output)
    if not config_path.is_absolute():
        config_path = ROOT / config_path
    if not output_path.is_absolute():
        output_path = ROOT / output_path
    if args.command == "render":
        render(config_path, output_path)
    else:
        check(config_path)


if __name__ == "__main__":
    main()
